name: Makefile CI

on:
  push:
    branches: [ "main" ]
 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: python-install
      uses: actions/setup-python@v2
      with:
         python-version: '3.x'

    - name: Install dependencies
      run: cd health-calculator-service
           && make install
    
    - name: Build
      run: cd health-calculator-service
           && make build
  
    - name: Test
      run: cd health-calculator-service
           && make test

    - name: Test_api
      run: cd health-calculator-service
           && make test_api

    - name: run
      run: cd health-calculator-service 
           && make run
